Production.MVC/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Business.Abstraction;
using Business.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Production.MVC.Controllers
{
    public class DetailsController : Controller
    {
        private readonly IDetailService _detailService;

        public DetailsController(IDetailService detailService)
        {
            _detailService = detailService;
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult<IEnumerable<DetailModel>>> GetAll()
        {
            return View(_detailService.GetAll());
        }

        [HttpGet("{dateTime:datetime}")]
        public async Task<ActionResult<IEnumerable<DetailModel>>> GetByDate(DateTime dateTime)
        {
            var detail = _detailService.FindByDate(dateTime);

            return View(detail);
        }

        [HttpGet("{detailName}")]
        public async Task<ActionResult<DetailModel>> GetByName(string detailName)
        {
            var detail = _detailService.FindByName(detailName);

            return View(detail);
        }

        [HttpGet("{templateId:int}")]
        public async Task<ActionResult<DetailModel>> GetByTemplateId(int templateId)
        {
            var detail = await _detailService.FindByTemplateId(templateId);

            return View(detail);
        }

        [HttpDelete("{detailId}")]
        public async Task<ActionResult> DeleteById(int detailId)
        {
            await _detailService.DeleteById(detailId);

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(DetailModel detailModel)
        {
            await _detailService.Create(detailModel);

            return View(detailModel);
        }

        [HttpPut]
        public async Task<ActionResult> Update(DetailModel detailModel)
        {
            await _detailService.UpdateAsync(detailModel);

            return View(detailModel);
        }
    }
}

Production.MVC/Views/Shared/_DetailPartial.cshtml
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Details"
           asp-action="GetAll">
            Details
        </a>
    </li>
</ul>

Production.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Production.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Production</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <partial name="_DetailPartial"/>

                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Production.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>